### ISSUE TITLE
Failed to determine best cudnn convolution algorithm

### ISSUE THREAD

**Issue by lawik** [elixir-nx/nx#1000]
Got this error trying a Bumblebee resnet example on GPU. Maybe that's expected?

```
** (RuntimeError) Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[1,112,112,64]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,224,224,3]{2,1,3,0} %copy, f32[7,7,3,64]{1,0,2,3} %copy.1), window={size=7x7 stride=2x2 pad=3_3x3_3}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: UNIMPLEMENTED: DNN library is not found.

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.
    (exla 0.4.1) lib/exla/computation.ex:92: EXLA.Computation.unwrap!/1
    (exla 0.4.1) lib/exla/computation.ex:61: EXLA.Computation.compile/4
    (exla 0.4.1) lib/exla/defn.ex:411: anonymous fn/10 in EXLA.Defn.compile/7
    (exla 0.4.1) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (exla 0.4.1) lib/exla/defn.ex:398: EXLA.Defn.compile/7
    (exla 0.4.1) lib/exla/defn.ex:262: EXLA.Defn.__compile__/4
    /home/lawik/projects/elixir-models/anything.livemd#cell:pipnyk7p5draamd475qtvagwsyc4o6f5:9: (file)
```

From the Livebook:

```elixir
# Started on cuda118, doesn't seem to matter it still grabs my GPU
System.put_env("XLA_TARGET", "cpu")

# Tried, didn't change anything
# System.put_env("XLA_FLAGS", "--xla_gpu_cuda_data_dir=/usr/lib/cuda --xla_gpu_strict_conv_algorithm_picker=false")
Mix.install([
  {:bumblebee, "~> 0.1.0"},
  {:nx, "~> 0.4.1"},
  {:exla, "~> 0.4.1"},
  {:axon, "~> 0.3.1"},
  {:kino, "~> 0.8.0"}
])

Nx.global_default_backend(EXLA.Backend)
```

## Section

```elixir
System.get_env("XLA_TARGET")
```

```elixir
{:ok, resnet} = Bumblebee.load_model({:hf, "microsoft/resnet-50"})
{:ok, featurizer} = Bumblebee.load_featurizer({:hf, "microsoft/resnet-50"})
```

```elixir
serving = Bumblebee.Vision.image_classification(resnet, featurizer)

image_input = Kino.Input.image("Image", size: {224, 224})
```

```elixir
image = Kino.Input.read(image_input)

# Build a tensor from the raw pixel data
image =
  image.data
  |> Nx.from_binary(:u8)
  |> Nx.reshape({image.height, image.width, 3})

Nx.Serving.run(serving, image)
```

Some logs:

```
09:54:01.711 [info] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

09:54:01.711 [info] XLA service 0x7f7f5c01b280 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:

09:54:01.711 [info]   StreamExecutor device (0): NVIDIA GeForce RTX 3070, Compute Capability 8.6

09:54:01.711 [info] Using BFC allocator.

09:54:01.711 [info] XLA backend allocating 5619076300 bytes on device 0 for BFCAllocator.

09:54:10.916 [info] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

09:54:12.106 [error] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

09:54:12.110 [error] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

09:54:12.111 [error] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by lawik** [comment]
If it shouldn't be run on the GPU for some reason that's cool I guess. It ran fine on CPU.

**Comment by josevalim** [comment]
This is often due to mismatched CUDA versions. What is your CUDA version and which XLA_TARGET have you set?

See hexdocs.pm/exla docs if you want to change the default client to CPU in this case.

**Comment by lawik** [comment]
Ah, gotcha. Probably that. Will try to confirm.

**Comment by josevalim** [comment]
you may also need to update cudnn in your machine. See min versions here: https://github.com/elixir-nx/xla/ - welcome to versioning cuda pains :)

**Comment by lawik** [comment]
First fixed my Cuda to 11.8.
Then cudnn was gone again so installed that and got libcudnn8 8.7.0.84-1+cuda11.8

```
/usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

Still got a failure...


```
** (RuntimeError) Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[1,112,112,64]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,224,224,3]{2,1,3,0} %copy, f32[7,7,3,64]{1,0,2,3} %copy.1), window={size=7x7 stride=2x2 pad=3_3x3_3}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: INTERNAL: All algorithms tried for %cudnn-conv = (f32[1,112,112,64]{2,1,3,0}, u8[0]{0}) custom-call(f32[1,224,224,3]{2,1,3,0} %copy, f32[7,7,3,64]{1,0,2,3} %copy.1), window={size=7x7 stride=2x2 pad=3_3x3_3}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm.  Per-algorithm errors:
  Profiling failure on cuDNN engine eng34{k2=1,k4=3,k5=1,k6=0,k7=0,k19=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng34{k2=1,k4=2,k5=1,k6=0,k7=0,k19=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{k2=3,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng48{k2=2,k6=0,k13=2,k14=0,k22=1}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng48{k2=2,k6=0,k13=2,k14=0,k22=2}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng34{k2=0,k4=2,k5=1,k6=0,k7=0,k19=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng48{k2=15,k6=0,k13=0,k14=0,k22=1}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng48{k2=15,k6=0,k13=0,k14=0,k22=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng1{k2=4,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{k2=0,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{k2=2,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng1{k2=2,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng1{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng55{k2=1,k13=0,k14=3,k18=1,k22=2,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng55{k2=0,k13=2,k14=3,k18=1,k22=2,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{k2=1,k3=0}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng55{k2=6,k13=2,k14=2,k18=1,k22=0,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng53{k2=5,k13=1,k14=2,k18=1,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng1{}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng28{}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng39{k2=0,k12=-1,k13=2,k14=3,k15=0,k17=3,k18=1,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng54{k2=1,k12=1,k13=0,k14=3,k15=0,k17=2,k18=1,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng56{k2=5,k12=1,k13=1,k14=2,k15=0,k17=2,k18=1,k22=0,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng53{k2=6,k13=0,k14=1,k18=1,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng56{k2=8,k12=1,k13=1,k14=3,k15=0,k17=2,k18=1,k22=0,k23=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'
  Profiling failure on cuDNN engine eng4{}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(4649): 'status'

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.
    (exla 0.4.1) lib/exla/computation.ex:92: EXLA.Computation.unwrap!/1
    (exla 0.4.1) lib/exla/computation.ex:61: EXLA.Computation.compile/4
    (exla 0.4.1) lib/exla/defn.ex:411: anonymous fn/10 in EXLA.Defn.compile/7
    (exla 0.4.1) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (exla 0.4.1) lib/exla/defn.ex:398: EXLA.Defn.compile/7
    (exla 0.4.1) lib/exla/defn.ex:262: EXLA.Defn.__compile__/4
    /home/lawik/projects/elixir-models/anything.livemd#cell:37pteio7jhcr4chznykanqpayin66o24:9: (file)

```

**Comment by josevalim** [comment]
And did you set XLA_TARGET to cuda118?

**Comment by lawik** [comment]
Yup :)

**Comment by lawik** [comment]
Someone said they ran into this and it turned out to be an Out of Memory problem. So maybe that's it. This didn't seem that big a model though.

**Comment by seanmor5** [comment]
@lawik Sometimes these errors are actually masking OOM errors, the first thing I would try is setting EXLA as your default compiler as well

After that, you can try playing with `:memory_fraction`

**Comment by lawik** [comment]
Will try @seanmor5

**Comment by lawik** [comment]
Memory thing worked. This ended up being my working setup:

```
System.put_env("XLA_TARGET", "cuda118")

Mix.install([
  {:bumblebee, "~> 0.1.0"},
  {:nx, "~> 0.4.1"},
  {:exla, "~> 0.4.1"},
  {:axon, "~> 0.3.1"},
  {:kino, "~> 0.8.0"}
  ],
config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA]   
    ],
    exla: [
      clients: [
        cuda: [memory_fraction: 0.6, platform: :cuda]
      ]
    ]
  ]
)

Nx.global_default_backend(EXLA.Backend)
```

**Comment by lawik** [comment]
I would have never guessed memory from the error :)

**Comment by seanmor5** [comment]
Nice! Note you can also stop the `memory_fraction` stuff by setting `preallocate: false`

I am a bit surprised that lowering the memory fraction worked for you. The preallocation acts as a hard upper-limit of GPU memory that XLA will consume. Lowering the fraction would make sense if you happen to have other GPU intensive processes running as the default is to try to claim 90% of GPU memory (which would contend with other processes)

To others who may come across this, AFAIK TensorFlow (and hence XLA) uses a memory pool to manage GPU memory and preallocation claims all of the memory it needs up front---which IIUC is more performant than forcing the pool to grow dynamically. If you have weird CUDA errors you *might* be able to fix them by messing with `memory_fraction` and `preallocate` options as they may be a result of OOMs. Disabling preallocation though might have a performance impact
